### ISSUE TITLE
$SAMPLE.$GRAPH.vcf.gz in the decompstion step

### ISSUE THREAD

**Issue by baozg** [wwliao/hpp_freeze1_pangenome_graph_qc#1]
Hi, @wwliao 

I try to follow your approach to compare the `vg deconstruct` from PGGB graph and ref-based callset. But I am confused by the sixth step in the decompstion.

In the readme, you mentioned that  $SAMPLE.$GRAPH.vcf.gz should be input the `decompose_graph_variants.py`. But the last step only have `*consistent.biallelic.vcf.gz`. Is this one should be supposed to use?

```bash
python3 decompose_graph_variants.py -o $SAMPLE.$GRAPH.decomposed.unsorted.vcf.gz \
                                       $GRAPH.pg \
                                       $SAMPLE.$GRAPH.vcf.gz \
    && bcftools sort -m 10G \
                     -T $SAMPLE_sort_tmp/ \
                     -Oz -o $SAMPLE.$GRAPH.decomposed.vcf.gz \
                     $SAMPLE.$GRAPH.decomposed.unsorted.vcf.gz \
    && bcftools index -t $SAMPLE.$GRAPH.decomposed.vcf.gz \
    && rm $SAMPLE.$GRAPH.decomposed.unsorted.vcf.gz
```

**Comment by wwliao** [comment]
Thank you for pointing out the inconsistency in the README. You are correct that in the sixth step of the decomposition, `$SAMPLE.$PREFIX.consistent.biallelic.vcf.gz` should be used as the input for `decompose_graph_variants.py`, not `$SAMPLE.$GRAPH.vcf.gz`. Sorry for the confusion and will update the README accordingly.

**Comment by baozg** [comment]
Thanks for the prompt reply. But it seems should be `$SAMPLE.$PREFIX.consistent.biallelic.vcf.gz` not the `$SAMPLE.$PREFIX.consistent.vcf.gz`

**Comment by wwliao** [comment]
Thank you for catching the typo in my previous response! I have fixed it.
